# Generated by Django 5.2.1 on 2025-05-20 03:19

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donaredapp', '0007_item_direccion_item_latitude_item_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
            ],
            options={
                'verbose_name': 'Item del Mapa',
                'verbose_name_plural': 'Items del Mapa',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('donaredapp.item',),
        ),
    ]
